# Generated by Django 6.0.4 on 2026-04-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='id',
        ),
        migrations.AddField(
            model_name='human',
            name='Id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
