# Generated by Django 6.0.4 on 2026-05-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0002_remove_human_id_human_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
