# Generated by Django 6.0.4 on 2026-05-08 19:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0003_alter_human_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 8, 23, 25, 27, 937494))),
                ('amount', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webb.human')),
            ],
        ),
    ]
