# Generated by Django 6.0.4 on 2026-05-22 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0004_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 22, 22, 12, 43, 382827)),
        ),
    ]
