# Generated by Django 6.0.4 on 2026-05-31 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0009_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 31, 22, 59, 15, 503407)),
        ),
    ]
