# Generated by Django 6.0.4 on 2026-06-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0011_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 6, 1, 18, 56, 0, 136188)),
        ),
    ]
