# Generated by Django 6.0.4 on 2026-06-01 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0015_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 6, 1, 21, 19, 35, 64001)),
        ),
    ]
